name: Build Docker image and push to GitHub Container Registry
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to GitHub Container Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: mutantmonkey/mmvoicemail
        username: mutantmonkey
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tag_names: true
